CREATE DATABASE IF NOT EXISTS alx_book_store;

USE alx_book_store;

-- Create Authors table
CREATE TABLE Authors (
    author_id INT PRIMARY KEY AUTO_INCREMENT,
    author_name VARCHAR(215) NOT NULL
);

-- Create Books table
CREATE TABLE Books (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    author_id INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    FOREIGN KEY (author_id) REFERENCES Authors (author_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create Customers table
CREATE TABLE Customers (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    email VARCHAR(215) UNIQUE,
    address TEXT
);

-- Create Orders table
CREATE TABLE Orders (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers (CUSTOMER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create Order_Details table
CREATE TABLE Order_Details (
    ORDERDETAILID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    quantity DOUBLE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES Orders (ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES Books (BOOK_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
