CREATE DATABASE IF NOT EXISTS alx_book_store;

USE alx_book_store;

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    author_id INT PRIMARY KEY AUTO_INCREMENT,
    author_name VARCHAR(215) NOT NULL
);

-- Create BOOKS table
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    author_id INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    FOREIGN KEY (author_id) REFERENCES AUTHORS (author_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    email VARCHAR(215) UNIQUE,
    address TEXT
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Create ORDER_DETAILS table
CREATE TABLE ORDER_DETAILS (
    ORDERDETAILID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    quantity DOUBLE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
